name: Deploy to GitHub pages

on:
  push:
    branches: ["main"]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-godot:
    runs-on: ubuntu-latest
    env:
      GODOT_VERSION: 4.3
    container:
      image: barichello/godot-ci:4.3
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Build
        run: |
          mkdir build
          cd godot-project
          godot --headless --export-release Web $(dirname $(pwd))/build/index.html
      - name: Fix problem with Github Pages headers
        run: |
          cd build
          wget https://raw.githubusercontent.com/gzuidhof/coi-serviceworker/master/coi-serviceworker.min.js 
          sed  '/\<head\>/a \<script src="coi-serviceworker.min.js"\>\</script\>' index.html > temp.html
          mv temp.html index.html
      - uses: actions/upload-artifact@v4
        with:
          name: godot
          path: build

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: [build-godot, build-svelte]
    steps:
      - uses: actions/configure-pages@v4
      - uses: actions/download-artifact@v4
      - uses: actions/upload-pages-artifact@v3
        with:
          path: godot
      - uses: actions/deploy-pages@v4
        id: deployment
